package dk.brics.tajs.test.stats;

import dk.brics.tajs.options.OptionValues;
import org.kohsuke.args4j.CmdLineException;

import java.io.IOException;
import java.util.Optional;

public class StatsStandard {

    public static String[][] testSunspider = {
            {"test-resources/src/sunspider/3d-cube.js"},
            {"test-resources/src/sunspider/3d-morph.js"},
            {"test-resources/src/sunspider/3d-raytrace.js"},
            {"test-resources/src/sunspider/access-binary-trees.js"},
            {"test-resources/src/sunspider/access-fannkuch.js"},
            {"test-resources/src/sunspider/access-nbody.js"},
            {"test-resources/src/sunspider/access-nsieve.js"},
            {"test-resources/src/sunspider/bitops-3bit-bits-in-byte.js"},
            {"test-resources/src/sunspider/bitops-bitwise-and.js"},
            {"test-resources/src/sunspider/bitops-nsieve-bits.js"},
            {"test-resources/src/sunspider/controlflow-recursive.js"},
            {"test-resources/src/sunspider/crypto-aes.js"},
            {"test-resources/src/sunspider/crypto-md5.js"},
            {"test-resources/src/sunspider/crypto-sha1.js"},
            {"-uneval", "test-resources/src/sunspider/date-format-tofte.js"},
            {"-uneval", "test-resources/src/sunspider/date-format-xparb.js"},
            {"test-resources/src/sunspider/math-cordic.js"},
            {"test-resources/src/sunspider/math-partial-sums.js"},
            {"test-resources/src/sunspider/math-spectral-norm.js"},
            {"test-resources/src/sunspider/regexp-dna.js"},
            {"test-resources/src/sunspider/string-base64.js"},
            {"test-resources/src/sunspider/string-fasta.js"},
            {"-uneval", "test-resources/src/sunspider/string-tagcloud.js"},
            {"test-resources/src/sunspider/string-unpack-code.js"},
            {"test-resources/src/sunspider/string-validate-input.js"},
    };

    public static String[][] testGoogle = {
            {"test-resources/src/google/richards.js"},
            {"test-resources/src/google/benchpress.js"},
            {"test-resources/src/google/splay.js"},
            {"test-resources/src/google/delta-blue.js"},
            {"test-resources/src/google/cryptobench.js"},
    };

    public static String[][] test10K = {
            {"test-resources/src/10k/10k_snake.html"},
            {"test-resources/src/10k/10k_world.html"},
            {"test-resources/src/10k/3d_maker.html"},
            {"test-resources/src/10k/attractor.html"},
            {"test-resources/src/10k/canvas_aquarium.html"},
            {"test-resources/src/10k/defend_yourself.html"},
            {"test-resources/src/10k/earth_night_lights.html"},
            {"test-resources/src/10k/filterrific.html"},
            {"test-resources/src/10k/flatwar.html"},
            {"-polyfill-mdn", "test-resources/src/10k/floating_bubbles.html"},
            {"-uneval", "test-resources/src/10k/fractal_landscape.html"},
            {"test-resources/src/10k/gravity.html"},
            {"test-resources/src/10k/heatmap.html"},
            {"test-resources/src/10k/last_man_standing.html"},
            {"test-resources/src/10k/lines.html"},
            {"test-resources/src/10k/minesweeper.html"},
            {"-uneval", "test-resources/src/10k/nbody.html"},
            {"test-resources/src/10k/rgb_color_wheel.html"},
            {"test-resources/src/10k/sinuous.html"},
            {"test-resources/src/10k/snowpar.html"},
            {"test-resources/src/10k/stairs_to_heaven.html"},
            {"test-resources/src/10k/sudoku.html"},
            {"test-resources/src/10k/tictactoe.html"},
            {"test-resources/src/10k/zmeyko.html"},
    };

    public static String[][] testChromeExperiments = {
            {"test-resources/src/chromeexperiments/3ddemo.html"},
            {"test-resources/src/chromeexperiments/anotherworld.html"},
            {"test-resources/src/chromeexperiments/apophis.html"},
            {"test-resources/src/chromeexperiments/aquarium.html"},
            {"test-resources/src/chromeexperiments/bingbong.html"},
            {"test-resources/src/chromeexperiments/blob.html"},
            {"test-resources/src/chromeexperiments/bomomo.html"},
            {"test-resources/src/chromeexperiments/breathinggalaxies.html"},
            {"test-resources/src/chromeexperiments/browserball.html"},
            {"test-resources/src/chromeexperiments/burncanvas.html"},
            {"test-resources/src/chromeexperiments/catchit.html"},
            {"test-resources/src/chromeexperiments/core.html"},
            {"test-resources/src/chromeexperiments/deepseastress.html"},
            {"test-resources/src/chromeexperiments/harmony.html"},
            {"test-resources/src/chromeexperiments/jstouch.html"},
            {"test-resources/src/chromeexperiments/kaleidoscope.html"},
            {"test-resources/src/chromeexperiments/keylight.html"},
            {"test-resources/src/chromeexperiments/liquidparticles.html"},
            {"test-resources/src/chromeexperiments/magnetic.html"},
            {"test-resources/src/chromeexperiments/orangetunnel.html"},
            {"test-resources/src/chromeexperiments/planedeformations.html"},
            {"test-resources/src/chromeexperiments/plasma.html"},
            {"test-resources/src/chromeexperiments/raytracer.html"},
            {"test-resources/src/chromeexperiments/sandtrap.html"},
            {"test-resources/src/chromeexperiments/starfield.html"},
            {"test-resources/src/chromeexperiments/strangeattractor.html"},
            {"-uneval", "test-resources/src/chromeexperiments/tetris.html"},
            {"test-resources/src/chromeexperiments/trail.html"},
            {"test-resources/src/chromeexperiments/tunneler.html"},
            {"test-resources/src/chromeexperiments/voronoi.html"},
            {"test-resources/src/chromeexperiments/voxels.html"},
            {"test-resources/src/chromeexperiments/watertype.html"},
    };

    public static String[][] test1K2012Love = {
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1001.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1005.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1008.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1010.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1015.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1018.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1019.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1024.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1025.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1027.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1028.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1030.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1031.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1041.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1044.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1045.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1047.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1048.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1050.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1053.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1054.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1055.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1057.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1061.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1063.js"},
            {"-uneval", "-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1066.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1068.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1071.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1072.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1079.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1091.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1092.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1093.js"},
            {"-uneval", "-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1095.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1102.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1103.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1107.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1113.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1115.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1120.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1134.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1140.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1143.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1148.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1149.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1154.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1155.js"},
            {"-uneval", "-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1156.js"},
            {"-uneval", "-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1157.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1160.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1163.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1166.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1168.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1169.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1170.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1171.js"},
            {"-uneval", "-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1175.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1176.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1183.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1186.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1188.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1189.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1190.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1191.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1195.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1196.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1199.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1201.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1203.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1209.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1218.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1219.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1224.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1225.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1229.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1230.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1232.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1240.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1243.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1245.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1246.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1247.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1249.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1250.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1251.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1252.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1254.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1257.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1258.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1260.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1265.js"},
            {"-uneval", "-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1269.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1270.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1271.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1274.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1275.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1276.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1279.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1280.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1281.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2012love/shim.js", "test-resources/src/1k2012love/1284.js"},
    };

    public static String[][] test1K2013Spring = {
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1307.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1309.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1310.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1311.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1316.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1319.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1323.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1334.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1336.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1337.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1344.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1345.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1350.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1358.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1360.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1362.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1375.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1376.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1377.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1379.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1384.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1388.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1392.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1398.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1400.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1404.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1411.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1415.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1417.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1420.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1421.js"},
            {"-uneval", "-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1423.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1425.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1426.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1427.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1428.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1429.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1430.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1436.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1437.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1438.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1442.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1443.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1449.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1450.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1454.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1457.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1458.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1462.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1470.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1472.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1473.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1475.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1478.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1479.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1483.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1484.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1486.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1498.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1502.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1506.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1507.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1510.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1511.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1514.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1524.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1525.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1526.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1528.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1529.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1533.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1535.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1536.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1537.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1539.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1541.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1542.js"},
            {"-uneval", "-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1544.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1547.js"},
            {"-dom", "-polyfill-mdn", "test-resources/src/1k2013spring/shim.js", "test-resources/src/1k2013spring/1557.js"},
    };

    public static String[][] testJQueryLoad = {
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.0.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.1.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.2.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.3.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.4.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.5.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.6.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.7.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.8.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.9.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.10.js"},
            {"-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.11.js"}
    };

    public static String[][] testJQueryLoad_ignoreUnreached = {
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.0.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.1.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.2.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.3.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.4.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.5.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.6.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.7.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.8.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.9.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.10.js"},
            {"-ignore-unreached", "-dom", "-uneval", "-determinacy", "benchmarks/tajs/src/jquery/libraries/jquery-1.11.js"}
    };

    public static void main(String[] args) throws IOException, CmdLineException {
        String outfile = args.length > 0 ? args[0] : "standard";
        OptionValues defaultOptions = new OptionValues();
        defaultOptions.getUnsoundness().setUseFixedRandom(true);
        defaultOptions.getUnsoundness().setShowUnsoundnessUsage(true);
        Stats.run(outfile, 60, 120000, Optional.of(defaultOptions),
                // from RunMedium:
                testSunspider,
                testGoogle,
                test10K,
                testChromeExperiments,
                test1K2012Love,
                test1K2013Spring,
                testJQueryLoad,
                testJQueryLoad_ignoreUnreached);
    }
}
